apiVersion: v2
description: Gotrust Docs
home: https://github.com/k8s-at-home/library-charts/tree/main/stable/common
keywords:
- k8s-at-home
- common
kubeVersion: '>=1.16.0-0'
maintainers:
- email: leminhphap2607@gmail.com
  name: leminhphap2607
name: common
type: library
version: 4.3.0
